# Generated by Django 5.1.1 on 2024-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fduser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='fduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
